name: master
on:
  push:
    branches:
      - master

jobs:
  build_a380x:
    name: Build and deploy A380X
    runs-on: ubuntu-latest
    env:
      FBW_PRODUCTION_BUILD: 1
      MASTER_PRE_RELEASE_ID: 66067756
      MASTER_PRE_RELEASE_TAG: assets/master
      MASTER_ZIP_NAME: A380X-master.7z
      VMASTER_PRE_RELEASE_ID: 32243965
      VMASTER_PRE_RELEASE_TAG: vmaster
      BUILD_DIR_NAME: master-a380x
      AIRCRAFT_PROJECT_PREFIX: a380x
      AIRCRAFT_VARIANT: a380-842
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set BUILT_DATE_TIME
        run: echo "BUILT_DATE_TIME=$(date -u -Iseconds)" >> $GITHUB_ENV
      - name: Create .env file
        run: |
          echo FBW_PRODUCTION_BUILD=1 >> fbw-a380x/.env
          echo CLIENT_ID=\"${{ secrets.NAVIGRAPH_CLIENT_ID_A380X }}\" >> fbw-a380x/.env
          echo CLIENT_SECRET=\"${{ secrets.NAVIGRAPH_CLIENT_SECRET_A380X }}\" >> fbw-a380x/.env
          echo CHARTFOX_SECRET=\"${{ secrets.CHARTFOX_SECRET }}\" >> fbw-a380x/.env
          echo SENTRY_DSN=\"${{ secrets.SENTRY_DSN }}\" >> fbw-a380x/.env
          echo AIRCRAFT_PROJECT_PREFIX=\"${{ env.AIRCRAFT_PROJECT_PREFIX }}\" >> fbw-a380x/.env
          echo AIRCRAFT_VARIANT=\"${{ env.AIRCRAFT_VARIANT }}\" >> fbw-a380x/.env
          echo BUILD_DIR_NAME=${{ env.BUILD_DIR_NAME }} >> .env
          echo LOCALAZY_READ_KEY=${{ secrets.LOCALAZY_READ_KEY }} >> .env
          echo VITE_BUILD=false >> .env
      - name: Install dependencies
        run: |
          ./scripts/dev-env/run.sh ./scripts/setup.sh --clean
      - name: Build A380X
        run: |
          ./scripts/dev-env/run.sh ./scripts/build_a380x.sh --no-tty -j 4
          rm -rf fbw-a380x/src
          docker system prune -af
      - name: Build ZIP files
        run: |
          df -h
          node ./scripts/fragment_a380x.js
          cp ./fbw-a380x/out/build-modules/modules.json ./fbw-a380x/out/flybywire-aircraft-a380-842/install.json
          node ./scripts/install-source_a380x.js
          mkdir ./${{ env.BUILD_DIR_NAME }}
          cd ./fbw-a380x/out/
          7z a -t7z -m0=lzma2 -mx=7 ../../${{ env.BUILD_DIR_NAME }}/${{ env.MASTER_ZIP_NAME }} ./flybywire-aircraft-a380-842/
          cd ../../
      - name: Upload ZIP to GitHub Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.MASTER_ZIP_NAME }}
          path: ./${{ env.BUILD_DIR_NAME }}/${{ env.MASTER_ZIP_NAME }}
